alter table CIFRA_DOCUMENT add constraint FK_CIFRA_DOCUMENT_CONTRAGENT foreign key (CONTRAGENT_ID) references CIFRA_CONTRAGENT(ID);
create index IDX_CIFRA_DOCUMENT_CONTRAGENT on CIFRA_DOCUMENT (CONTRAGENT_ID);
