alter table CIFRA_DOCUMENT add constraint FK_CIFRA_DOCUMENT_WAREHOUSE foreign key (WAREHOUSE_ID) references CIFRA_WAREHOUSE(ID);
create index IDX_CIFRA_DOCUMENT_WAREHOUSE on CIFRA_DOCUMENT (WAREHOUSE_ID);
