alter table CIFRA_JOURNAL add constraint FK_CIFRA_JOURNAL_RESPONSIBLE foreign key (RESPONSIBLE_ID) references CIFRA_EMPLOYEE(ID);
alter table CIFRA_JOURNAL add constraint FK_CIFRA_JOURNAL_HOLDER foreign key (HOLDER_ID) references CIFRA_EMPLOYEE(ID);
create index IDX_CIFRA_JOURNAL_RESPONSIBLE on CIFRA_JOURNAL (RESPONSIBLE_ID);
create index IDX_CIFRA_JOURNAL_HOLDER on CIFRA_JOURNAL (HOLDER_ID);
