alter table CIFRA_CHECK_LIST_ITEMS add constraint FK_CIFRA_CHECK_LIST_ITEMS_DOC_TYPE foreign key (DOC_TYPE_ID) references CIFRA_DOC_TYPE(ID);
alter table CIFRA_CHECK_LIST_ITEMS add constraint FK_CIFRA_CHECK_LIST_ITEMS_CHECK_LIST foreign key (CHECK_LIST_ID) references CIFRA_CHECK_LIST(ID);
create index IDX_CIFRA_CHECK_LIST_ITEMS_DOC_TYPE on CIFRA_CHECK_LIST_ITEMS (DOC_TYPE_ID);
create index IDX_CIFRA_CHECK_LIST_ITEMS_CHECK_LIST on CIFRA_CHECK_LIST_ITEMS (CHECK_LIST_ID);
