alter table CIFRA_DOCUMENT add constraint FK_CIFRA_DOCUMENT_ON_INITIATOR foreign key (INITIATOR_ID) references CIFRA_EMPLOYEE(ID);
create index IDX_CIFRA_DOCUMENT_ON_INITIATOR on CIFRA_DOCUMENT (INITIATOR_ID);
