alter table CIFRA_DOCUMENT add constraint FK_CIFRA_DOCUMENT_ON_DIVISION foreign key (DIVISION_ID) references CIFRA_DIVISION(ID);
create index IDX_CIFRA_DOCUMENT_ON_DIVISION on CIFRA_DOCUMENT (DIVISION_ID);
