alter table CIFRA_DOCUMENT add constraint FK_CIFRA_DOCUMENT_ON_COMPANY foreign key (COMPANY_ID) references CIFRA_COMPANY(ID);
create index IDX_CIFRA_DOCUMENT_ON_COMPANY on CIFRA_DOCUMENT (COMPANY_ID);
