alter table CIFRA_DOCUMENT add constraint FK_CIFRA_DOCUMENT_ON_DOC_CAUSE foreign key (DOC_CAUSE_ID) references CIFRA_DOCUMENT(ID);
create index IDX_CIFRA_DOCUMENT_ON_DOC_CAUSE on CIFRA_DOCUMENT (DOC_CAUSE_ID);
