alter table CIFRA_CHECK_LIST_ITEMS add constraint FK_CIFRA_CHECK_LIST_ITEMS_ON_DOC_TYPE foreign key (DOC_TYPE_ID) references CIFRA_DOC_TYPE(ID);
create index IDX_CIFRA_CHECK_LIST_ITEMS_ON_DOC_TYPE on CIFRA_CHECK_LIST_ITEMS (DOC_TYPE_ID);
