alter table CIFRA_DOCUMENT add constraint FK_CIFRA_DOCUMENT_ON_WF_INITIATOR foreign key (WF_INITIATOR_ID) references CIFRA_EMPLOYEE(ID);
create index IDX_CIFRA_DOCUMENT_ON_WF_INITIATOR on CIFRA_DOCUMENT (WF_INITIATOR_ID);
