alter table CIFRA_JOURNAL add constraint FK_CIFRA_JOURNAL_ON_RESPONSIBLE foreign key (RESPONSIBLE_ID) references CIFRA_EMPLOYEE(ID);
create index IDX_CIFRA_JOURNAL_ON_RESPONSIBLE on CIFRA_JOURNAL (RESPONSIBLE_ID);
