alter table TEMPLATE_TASK_TYPICAL_LINK add constraint FK_TEMTASTYP_ON_TASK_TEMPLATE foreign key (TASK_TEMPLATE_ID) references TASKS_TASK_TEMPLATE(ID);
alter table TEMPLATE_TASK_TYPICAL_LINK add constraint FK_TEMTASTYP_ON_TASK_TYPICAL foreign key (TASK_TYPICAL_ID) references TASKS_TASK_TYPICAL(ID);
