alter table CIFRA_DOCUMENT add constraint FK_CIFRA_DOCUMENT_ON_WORKFLOW foreign key (WORKFLOW_ID) references WFSTP_WORKFLOW(ID);
create index IDX_CIFRA_DOCUMENT_ON_WORKFLOW on CIFRA_DOCUMENT (WORKFLOW_ID);
