alter table CIFRA_DOCUMENT_ATTACHED_FILES_LINK add constraint FK_DOCATTFIL_ON_DOCUMENT foreign key (DOCUMENT_ID) references CIFRA_DOCUMENT(ID);
alter table CIFRA_DOCUMENT_ATTACHED_FILES_LINK add constraint FK_DOCATTFIL_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID);
